--NOTES:
--1. the table [greetings_words] is created at Django level with migrations
--   * cd /app
--   * python manage.py makemigrations
--   * python manage.py migrate
--
--2. the sample data is injected by SQL client script AFTER Django migrations
--   * cd /app
--   * sql/djangoapp_data_inject.sh
--
CREATE DATABASE djangoapp;
