#Build, Tag and share Docker Image to Docker Hub
name: build-docker-image

on:
  push:
    tags:
      - 'v*'
      #- '*'                    # push events to every tag not containing /
      #- '**'                   # push events to every tag including hierarchical tags like v1.0/beta
      #- 'v[12].[0-9]+.[0-9]+'  # matches all semantic versioning branches and tags with major version 1 or 2. for example: v1.10.1, v2.0.0
    #
    #branches:
    #  - main

env:
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}    #dotspace2019
  IMAGE_NAME: ${{ secrets.DOCKERHUB_REPO_NAME }} # nve-diploma-webapp
  #
  #..examples
  #IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code/repository
        uses: actions/checkout@v4
        #uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          #
          #..examples
          #registry: ${{ env.REGISTRY }}
          #username: ${{ github.actor }}
          #password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      #..doesnt_work :: file not found error
      #- name: Write Tags to APP_VERSION file
      #  run: |
      #    TAGS=${{ steps.meta.outputs.tags }}
      #    echo $TAGS > ./app/webapp/APP_VERSION

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #
          #..examples
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:test
